// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBL2yqciFS6SN0fZmPY1KukM-kOFLrgIo',
    appId: '1:673766512901:web:94757ec9a89a974dd33f6c',
    messagingSenderId: '673766512901',
    projectId: 'kuenpaapp',
    authDomain: 'kuenpaapp.firebaseapp.com',
    storageBucket: 'kuenpaapp.firebasestorage.app',
    measurementId: 'G-RYNERBQ86L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbed7P9ds1hMWjhcYmlXGMAvFZ8rk_gQ',
    appId: '1:673766512901:android:67e59bf4a7fae210d33f6c',
    messagingSenderId: '673766512901',
    projectId: 'kuenpaapp',
    storageBucket: 'kuenpaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEsohEU5BB7zI0ylN1w4DnJ1KXDIUhkQ',
    appId: '1:673766512901:ios:d75347a65a2d2d59d33f6c',
    messagingSenderId: '673766512901',
    projectId: 'kuenpaapp',
    storageBucket: 'kuenpaapp.firebasestorage.app',
    iosBundleId: 'com.example.kuenpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnEsohEU5BB7zI0ylN1w4DnJ1KXDIUhkQ',
    appId: '1:673766512901:ios:d75347a65a2d2d59d33f6c',
    messagingSenderId: '673766512901',
    projectId: 'kuenpaapp',
    storageBucket: 'kuenpaapp.firebasestorage.app',
    iosBundleId: 'com.example.kuenpa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBL2yqciFS6SN0fZmPY1KukM-kOFLrgIo',
    appId: '1:673766512901:web:f18af4c8b0537a2bd33f6c',
    messagingSenderId: '673766512901',
    projectId: 'kuenpaapp',
    authDomain: 'kuenpaapp.firebaseapp.com',
    storageBucket: 'kuenpaapp.firebasestorage.app',
    measurementId: 'G-4FW9W2JCZ5',
  );
}
